Feature/dkr 1 hangman
skorodenko/python pull request #4
Opened 2020-11-18 18:05 UTC by skorodenko

2020-11-19 19:31 UTC, Hozhyi requested changes

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +# secret_word while you're doing your own testing)
I think these comments are not needed any more

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +            if km != ko:
it's very hard to read that, please - name variables properly so that their meaning will be clear

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +    my_word = my_word.replace("_ ", "X")
You could just remove spaces, I don't think you need another symbol

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +    my_word = my_word.replace("_ ", "X")
And 1 more - the `my_word` most of the time is the same, so you can perform this replacement on 1 level up

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +    global wordlist
Do you really need this line here?

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +                        "Do you want to display them? y/n ")
Have you agreed this behavior with Product Owner?

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +            ans = input("There is more than 30 words that are suitable for hint."+
Is it really needed to have such short name of variable?

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +def hangman_with_hints(secret_word):
I believe most of the code here is same as in function `hangman()` - could you combine them in 1 function? To avoid code duplication

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +    ###############
Remove all comments that not needed

2020-11-19 19:31 UTC, Hozhyi commented on hangman.py
> +        stop = input("Do you want to quit the program. y/n ")
Is this behavior agreed with PO?

2020-11-20 15:34 UTC, skorodenko commented on hangman.py
> +    global wordlist
As far as I know, when you give an object as argument to function it creates a local version of it (uses more memory), providing that wordlist is list of great amount of words. That is why it is better to call wordlist global variable.

2020-11-22 23:25 UTC, Hozhyi requested changes

2020-11-22 23:25 UTC, Hozhyi commented on hangman.py
> +           get_available_letters(VARIABLES["letters_guessed"]).count("_ ") > 0:
It's hard for me to understand the meaning of that condition. Could you add some comments here?

2020-11-22 23:25 UTC, Hozhyi commented on hangman.py
> +        print("You play hangman without hints.")
Have you agreed that with PO?

2020-11-22 23:25 UTC, Hozhyi commented on hangman.py
> +        while VARIABLES["guesses_remaining"] > 0:
this is a business logic of game, and shouldn't be here. it's should be in scope of hangman function. Here you should only call `hangman`

2020-11-23 15:35 UTC, skorodenko commented on hangman.py
> +def guess_try(guess, VARIABLES):
I thought that container for important variables should be names like that (It is convenient as well).

2020-11-23 15:38 UTC, skorodenko commented on hangman.py
> +    VARIABLES: dictionary contining
I don`t really get your idea. Prove me wrong, by saying "You can't be sure that this dictionary will contain what you expect." you mean that there is a chance that docstring would differ from the contents of dictionary?

2020-11-24 15:40 UTC, skorodenko commented on hangman.py
> +        while VARIABLES["guesses_remaining"] > 0:
Changed:
Moved this part of code into detached function game_restart.

2020-11-24 15:40 UTC, Hozhyi commented on hangman.py
> +# -----------------------------------
Do you need this separator?

2020-11-24 15:43 UTC, skorodenko commented on hangman.py
> +           get_available_letters(VARIABLES["letters_guessed"]).count("_ ") > 0:
Added comment.

2020-11-24 15:44 UTC, skorodenko commented on hangman.py
> +def hangman(VARIABLES): # Hangman combined with Hangman with hints
Changed.

2020-11-24 15:46 UTC, skorodenko commented on hangman.py
> +def hangman(VARIABLES): # Hangman combined with Hangman with hints
Restored.

2020-11-24 15:47 UTC, skorodenko commented on hangman.py
> +def display(output, VARIABLES):
Added new docstring.

2020-11-24 15:47 UTC, skorodenko commented on hangman.py
> +    output: int, option to triger particular text output
Enum class created.

2020-11-24 15:47 UTC, skorodenko commented on hangman.py
> +    VARIABLES: dictionary contining
Created.

2020-11-24 15:48 UTC, skorodenko commented on hangman.py
> +                 "30 random suggestions will be printed."
Removed.

2020-11-24 15:48 UTC, skorodenko commented on hangman.py
> +                 f"There are {len(res)} suggsetions.\n"+
Removed.

2020-11-24 15:48 UTC, skorodenko commented on hangman.py
> +    for i in wordlist:
i changed to word.

2020-11-24 15:54 UTC, skorodenko commented on hangman.py
> +        else:
No, this else belongs to for statement.

2020-11-24 15:55 UTC, skorodenko commented on hangman.py
> +# -----------------------------------
No, therefore it is removed.

2020-11-25 15:40 UTC, skorodenko commented on hangman.py
> +    global wordlist
Removed global.

2020-11-25 15:42 UTC, closed without merging